steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/massive-concept-428309-a4/invoice-extract-genai-docker/cloud-run:$COMMIT_SHA",
        ".",
      ]
    
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/massive-concept-428309-a4/invoice-extract-genai-docker/cloud-run:$COMMIT_SHA",
      ]
    

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
          "run",
          "deploy",
          "genai-invoice-extract", 
          "--image",
          "us-central1-docker.pkg.dev/massive-concept-428309-a4/invoice-extract-genai-docker/cloud-run:$COMMIT_SHA",
          "--platform",
          "managed",
          "--region",
          "us-central1", 
          "--set-traffic",
          "latest=100"
      ]

  # serviceAccount: ""

  options:
    logging: CLOUD_LOGGING_ONLY

